### ISSUE TITLE
os.rename is not handled by the filesystem fixtures

### ISSUE THREAD

**Issue by tkuhlman** [freeekanayaka/systemfixtures#1]
I have code that uses os.rename to move a directory. When testing using the filesystem fixtures I get an error like,

    os.rename(HOME, self._backup_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/jenkins' -> '/var/lib/jenkins.bak'

The directory '/var/lib' is under a filesystem fixture and other commands to it are working fine.

**Comment by tkuhlman** [comment]
I worked around the issue, in https://github.com/jenkinsci/jenkins-charm/pull/18/files#diff-4b461654aab3edc991b97e5f9a71be65R21

**Comment by freeekanayaka** [comment]
This should be now fixed. I've made a new 0.6.4 release, so if you modify the tox.ini file in your jenkins branch like this:

```
deps =
    -r{toxinidir}/requirements.txt
    fixtures
    systemfixtures>=0.6.4
    charm-test>=0.2.0
    fakesleep
    coverage
```

(notice the new systemfixtures entry) you should be able to drop the workaround.

**Comment by tkuhlman** [comment]
Thanks I just confirmed that the fix works.
